GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJLZXZpbiIsImlhdCI6MTU2MzI4OTQ3OCwiZXhwIjoxNTYzMjkzMDc4fQ.ILkUzhw82KHCg572yDZBAaR192fCERhqgsG9opfy-Yo
###
POST http://localhost:3000/register
Content-Type: application/json

{
  "firstName": "Amandine",
  "lastName": "Ripoll",
  "email": "amandine-ripoll@outlook.fr",
  "password": "amandine",
  "dob": "2018-05-12"
}

###
POST http://localhost:3000/login_check
Content-Type: application/json

{
  "email": "amandine-ripoll@outlook.fr",
  "password": "amandine"
}

###
POST http://localhost:3000/goods
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJLZXZpbiIsImlhdCI6MTU2MzI4OTQ3OCwiZXhwIjoxNTYzMjkzMDc4fQ.ILkUzhw82KHCg572yDZBAaR192fCERhqgsG9opfy-Yo

{
  "address": "4 bis rue Leon Blum",
  "zipcode": "91300",
  "city": "massy",
  "price": "200000",
  "description": "Superbe appartement lumineux dans le nouveau quartier de Massy",
  "title": "Appartement 4 pièce à Massy",
  "room":4,
  "bedroom": 3,
  "square_meters":85,
  "status":1,
  "type":"Buy",
  "id_user":"1"
}

###
POST http://localhost:3000/images
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJBbWFuZGluZSIsImlhdCI6MTU2MzM1Mzc1NSwiZXhwIjoxNTYzMzU3MzU1fQ.bzFu6CuDOL6WdGi8B9OyFVAkNEekZratMxN8Zyo2PTQ

{
  "path": "ddfsdfrhdfdgd.png",
  "id_good": "1"
}

