###
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NjM3MTk1NzAsImV4cCI6MTU2MzcyMzE3MH0.XvMjKmkO2vWOC_Fw8ZxEEZF15vvxMz-4TxfTGVf6MBM

###
POST http://localhost:3000/register
Content-Type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJFbnpvIiwiaWF0IjoxNTYzNTQ1MjE3LCJleHAiOjE1NjM1NDg4MTd9.2UvY67xaI573masmllJzMCE3mfrXwFvdHstJ82ZTaRg

{
  "firstName": "test",
  "lastName": "test",
  "email": "test@gmail.com",
  "password": "test",
  "dob": "2018-05-12"
}

###
PUT http://localhost:3000/users/edit/5d3190c4a0ed2b001ed9335b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJBbWFuZGluZSIsImlhdCI6MTU2MzUyODE3MywiZXhwIjoxNTYzNTMxNzczfQ.oFEbCtgyrmImlXruCaos0dpoEOySamgd6a5YWEJm7yE

{
  "firstName": "test",
  "lastName": "test",
  "email": "test@gmail.com",
  "password": "123456",
  "dob": "2018-05-12"
}

###
DELETE http://localhost:3000/users/delete/5d318b859bc632002039b1ab
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJBbWFuZGluZSIsImlhdCI6MTU2MzUyODE3MywiZXhwIjoxNTYzNTMxNzczfQ.oFEbCtgyrmImlXruCaos0dpoEOySamgd6a5YWEJm7yE

###
POST http://localhost:3000/login_check
Content-Type: application/json

{
  "email": "amandine-ripoll@outlook.fr",
  "password": "amandine"
}

###
GET http://localhost:3000/goods
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJBbWFuZGluZSIsImlhdCI6MTU2Mzc0NDQyMSwiZXhwIjoxNTYzNzQ4MDIxfQ.36VAtCK_WYjfRNSHBKsACztgSijrkHiiu1n6Hd6FASQ

###
GET http://localhost:3000/goods/user/5d3484937b53c9002e862d96
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NjM3MjI5NDQsImV4cCI6MTU2MzcyNjU0NH0.yalUBASmsNkEcb4z6DfrwzTrTNDXwTj-hizhl0IF3Xo

###
PUT http://localhost:3000/goods/edit/5d2ef9ed4ae6a70168b20522
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJBbWFuZGluZSIsImlhdCI6MTU2MzM1ODY0NCwiZXhwIjoxNTYzMzYyMjQ0fQ.64hl9zkpQwnYT9rKwlzxiMHU9D3JpDMXRHLArNwm0T0

{
  "address": null,
  "zipcode": 93150,
  "city": null,
  "price": null,
  "description": null,
  "title": null,
  "room": null,
  "bedroom": null,
  "square_meters": null,
  "status": null,
  "type": null
}

###
GET http://localhost:3000/goods
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJ0ZXN0IiwiaWF0IjoxNTYzNzIxNTMyLCJleHAiOjE1NjM3MjUxMzJ9.j7pysqDkXh_EKoMmS1hr80G-WyBlC35U86YsF3n8Py8

{
  "address": "4 bis rue Leon Blum",
  "zipcode": "91300",
  "city": "Massy",
  "price": "200000",
  "description": "Superbe appartement lumineux dans le nouveau quartier de Massy",
  "title": "Appartement 5 pièce à Massy",
  "room":5,
  "bedroom": 3,
  "square_meters":85,
  "status":1,
  "type":"louer",
  "id_user":"1"
}

###
PUT http://localhost:3000/goods/edit/5d318d959bc632002039b1ae
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJBbWFuZGluZSIsImlhdCI6MTU2MzUyODE3MywiZXhwIjoxNTYzNTMxNzczfQ.oFEbCtgyrmImlXruCaos0dpoEOySamgd6a5YWEJm7yE

{
  "address": "4 bis rue Leon Blum",
  "zipcode": "91300",
  "city": "paris",
  "price": "200000",
  "description": "Superbe appartement lumineux dans le nouveau quartier de Massy",
  "title": "Appartement 4 pièce à Massy",
  "room":4,
  "bedroom": 3,
  "square_meters":85,
  "status":1,
  "type":"Buy",
  "id_user":"1"
}

###
GET http://localhost:3000/images
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NjM3MzYzODksImV4cCI6MTU2MzczOTk4OX0.XlP2VQe7kg21YGOgMk-I7EYBCdkR4YZhMZ72uqRqVU0
